name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      backend:
        image: node:18
        ports:
          - 5000:5000
        options: >-
          --health-cmd "curl -f http://localhost:5000/api || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend
        working-directory: ./client
        run: npm install

      - name: Install backend
        working-directory: ./server
        run: npm install

      - name: Run frontend tests
        working-directory: ./client
        run: npm test -- --watchAll=false

      - name: Run backend tests
        working-directory: ./server
        run: npm test

      - name: Run E2E tests
        run: |
          npm install -D playwright
          npx playwright install
          npm run test:e2e

